package com.example.newsapp.ml

import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory

/**
 * ML Model artifacts data structure
 * 
 * Contains embeddings and metadata from trained ALS/SVD model.
 * These artifacts are generated by Firebase Cloud Function and
 * downloaded by the app for on-device inference.
 * 
 * Structure:
 * - User embeddings: userId → vector[50]
 * - Article embeddings: articleId → vector[50]
 * - Biases: Learned biases for users and articles
 * - Metadata: Version, accuracy, training info
 */
@JsonClass(generateAdapter = true)
data class ML_ModelArtifacts(
    // User embeddings (userId → latent vector)
    val userEmbeddings: Map<String, List<Float>>,
    
    // Article embeddings (articleId → latent vector)
    val articleEmbeddings: Map<String, List<Float>>,
    
    // User-specific biases
    val userBiases: Map<String, Float> = emptyMap(),
    
    // Article-specific biases
    val articleBiases: Map<String, Float> = emptyMap(),
    
    // Global mean rating
    val globalMean: Float = 0f,
    
    // Model metadata
    val version: String,
    val trainedAt: Long,
    val accuracy: Float = 0f,
    val embeddingDimension: Int = 50,
    
    // Statistics
    val userCount: Int = 0,
    val articleCount: Int = 0,
    val interactionCount: Int = 0
) {
    
    /**
     * Get embedding dimension (should be consistent)
     */
    fun getEmbeddingSize(): Int {
        return userEmbeddings.values.firstOrNull()?.size ?: embeddingDimension
    }
    
    /**
     * Check if model has embedding for user
     */
    fun hasUserEmbedding(userId: String): Boolean {
        return userEmbeddings.containsKey(userId)
    }
    
    /**
     * Check if model has embedding for article
     */
    fun hasArticleEmbedding(articleId: String): Boolean {
        return articleEmbeddings.containsKey(articleId)
    }
    
    /**
     * Get user embedding or default (zero vector)
     */
    fun getUserEmbedding(userId: String): FloatArray {
        return userEmbeddings[userId]?.toFloatArray() 
            ?: FloatArray(embeddingDimension) { 0f }
    }
    
    /**
     * Get article embedding or default (zero vector)
     */
    fun getArticleEmbedding(articleId: String): FloatArray {
        return articleEmbeddings[articleId]?.toFloatArray()
            ?: FloatArray(embeddingDimension) { 0f }
    }
    
    /**
     * Get user bias or default
     */
    fun getUserBias(userId: String): Float {
        return userBiases[userId] ?: 0f
    }
    
    /**
     * Get article bias or default
     */
    fun getArticleBias(articleId: String): Float {
        return articleBiases[articleId] ?: 0f
    }
    
    /**
     * Serialize to JSON string
     */
    fun toJson(): String {
        val moshi = Moshi.Builder()
            .add(KotlinJsonAdapterFactory())
            .build()
        val adapter = moshi.adapter(ML_ModelArtifacts::class.java)
        return adapter.toJson(this)
    }
    
    /**
     * Calculate approximate size in bytes
     */
    fun estimateSizeBytes(): Long {
        val embeddingSize = embeddingDimension * 4L // 4 bytes per float
        val totalEmbeddings = (userCount + articleCount).toLong()
        val embeddingsBytes = totalEmbeddings * embeddingSize
        val biasesBytes = (userCount + articleCount) * 4L
        val metadataBytes = 1024L // ~1KB for metadata
        
        return embeddingsBytes + biasesBytes + metadataBytes
    }
    
    /**
     * Validate model integrity
     */
    fun validate(): Boolean {
        // Check embedding dimensions are consistent
        val userEmbedSize = userEmbeddings.values.firstOrNull()?.size ?: embeddingDimension
        val articleEmbedSize = articleEmbeddings.values.firstOrNull()?.size ?: embeddingDimension
        
        if (userEmbedSize != articleEmbedSize) {
            android.util.Log.e(TAG, "Embedding dimension mismatch: user=$userEmbedSize, article=$articleEmbedSize")
            return false
        }
        
        // Check counts match
        if (userEmbeddings.size != userCount || articleEmbeddings.size != articleCount) {
            android.util.Log.w(TAG, "Count mismatch: expected users=$userCount, got=${userEmbeddings.size}")
        }
        
        // Check for empty embeddings
        if (userEmbeddings.isEmpty() || articleEmbeddings.isEmpty()) {
            android.util.Log.e(TAG, "Empty embeddings detected")
            return false
        }
        
        return true
    }
    
    companion object {
        private const val TAG = "ML_ModelArtifacts"
        
        /**
         * Deserialize from JSON string
         */
        fun fromJson(json: String): ML_ModelArtifacts? {
            return try {
                val moshi = Moshi.Builder()
                    .add(KotlinJsonAdapterFactory())
                    .build()
                val adapter = moshi.adapter(ML_ModelArtifacts::class.java)
                adapter.fromJson(json)
            } catch (e: Exception) {
                android.util.Log.e(TAG, "Failed to parse model artifacts", e)
                null
            }
        }
        
        /**
         * Create empty/default model (for cold start)
         */
        fun createDefault(): ML_ModelArtifacts {
            return ML_ModelArtifacts(
                userEmbeddings = emptyMap(),
                articleEmbeddings = emptyMap(),
                userBiases = emptyMap(),
                articleBiases = emptyMap(),
                globalMean = 2.5f,
                version = "default",
                trainedAt = System.currentTimeMillis(),
                accuracy = 0f,
                embeddingDimension = 50,
                userCount = 0,
                articleCount = 0,
                interactionCount = 0
            )
        }
    }
}
